DEFAULTS = {
    'shared': {
        'company_name': {'en': 'S3 Synergy', 'bg': 'S3 Синерджи'},
        'slogan': {'en': 'Driven by Innovation, Defined by Quality.', 'bg': 'Водени от иновации, определени от качество.'},
        'footer_text': {'en': '© 2025 S3 Synergy Ltd. All rights reserved. Website made by S. Sotirov.', 'bg': '© 2025 S3 Synergy Ltd. Всички права запазени. Уебсайт от С. Сотиров.'},
        'nav_home': {'en': 'Home', 'bg': 'Начало'},
        'nav_services': {'en': 'Services', 'bg': 'Услуги'},
        'nav_projects': {'en': 'Projects', 'bg': 'Проекти'},
        'nav_contact': {'en': 'Contact', 'bg': 'Контакт'},
    },
    'home': {
        'hero_title': {'en': 'Welcome to S3 Synergy Ltd', 'bg': 'Добре дошли в S3 Synergy Ltd'},
        'hero_subtitle': {'en': 'Expert engineering solutions tailored for your business.', 'bg': 'Експертни инженерни решения, специално за вашия бизнес.'},
        'hero_btn_services': {'en': 'Explore Services', 'bg': 'Разгледайте услугите'},
        'hero_btn_contact': {'en': 'Contact Us', 'bg': 'Свържете се с нас'},
        'stat1_num': {'en': '10+', 'bg': '10+'},
        'stat1_label': {'en': 'Years of Experience', 'bg': 'Години опит'},
        'stat2_num': {'en': '50+', 'bg': '50+'},
        'stat2_label': {'en': 'Projects Completed', 'bg': 'Завършени проекти'},
        'stat3_num': {'en': '4', 'bg': '4'},
        'stat3_label': {'en': 'Core Service Areas', 'bg': 'Основни услуги'},
        'stat4_num': {'en': '100%', 'bg': '100%'},
        'stat4_label': {'en': 'Client Satisfaction', 'bg': 'Удовлетвореност на клиентите'},
        'activities_title': {'en': 'ACTIVITIES AND SERVICES', 'bg': 'ДЕЙНОСТИ И УСЛУГИ'},
        'act1_title': {'en': 'Conceptual & Technical Design', 'bg': 'Идейно и техническо проектиране'},
        'act1_desc': {'en': 'From initial concepts to detailed designs, we plan and execute robust engineering projects.', 'bg': 'От първоначални идеи до детайлни проекти, ние планираме и реализираме стабилни инженерни проекти.'},
        'act2_title': {'en': 'Simulation & Analysis', 'bg': 'Симулация и анализ'},
        'act2_desc': {'en': 'State-of-the-art simulation tools to ensure efficiency and reliability in energy systems.', 'bg': 'Съвременни симулационни инструменти за гарантиране на ефективност и надеждност в енергийните системи.'},
        'act3_title': {'en': 'Structural & Strength Analysis', 'bg': 'Якостен анализ'},
        'act3_desc': {'en': 'Comprehensive quality checks and analysis ensuring compliance and structural integrity.', 'bg': 'Пълноценни проверки за качество и анализ, гарантиращи съответствие и структурна цялост.'},
        'act4_title': {'en': 'Custom Mechanical Design', 'bg': 'Персонализирано механично проектиране'},
        'act4_desc': {'en': 'Tailored designs for components, assemblies, and entire systems to match your needs.', 'bg': 'Персонализирани решения за компоненти, сглобки и цели системи според вашите нужди.'},
        'projects_title': {'en': 'LATEST PROJECTS', 'bg': 'ПОСЛЕДНИ ПРОЕКТИ'},
        'proj1_title': {'en': 'Solar Power Plant Installation', 'bg': 'Инсталация на слънчева електроцентрала'},
        'proj1_desc': {'en': 'Turnkey installation and commissioning of a 5MW solar power facility, including grid integration.', 'bg': 'Цялостна инсталация и въвеждане в експлоатация на 5MW соларна електроцентрала, включително свързване към мрежата.'},
        'proj2_title': {'en': 'Industrial Automation Upgrade', 'bg': 'Модернизация на индустриална автоматизация'},
        'proj2_desc': {'en': 'Modernization of control systems for improved efficiency and safety in manufacturing processes.', 'bg': 'Модернизация на системи за управление за подобрена ефективност и безопасност в производствените процеси.'},
        'proj3_title': {'en': 'Waste Management Solutions', 'bg': 'Решения за управление на отпадъци'},
        'proj3_desc': {'en': 'Design and implementation of eco-friendly waste processing and recycling systems.', 'bg': 'Проектиране и внедряване на екологични системи за преработка и рециклиране на отпадъци.'},
        'proj4_title': {'en': 'Energy Storage Integration', 'bg': 'Интеграция на енергийно съхранение'},
        'proj4_desc': {'en': 'Deployment of advanced battery storage to support renewable energy and grid stability.', 'bg': 'Внедряване на съвременни батерийни системи за съхранение в подкрепа на възобновяемата енергия и стабилността на мрежата.'},
        'cta_title': {'en': 'Ready to Start Your Project?', 'bg': 'Готови ли сте да започнете проекта си?'},
        'cta_desc': {'en': 'Let our experienced team bring your engineering vision to life.', 'bg': 'Оставете нашия опитен екип да даде живот на вашата инженерна идея.'},
        'cta_btn': {'en': 'Contact Us', 'bg': 'Свържете се с нас'},
    },
    'services': {
        'hero_title': {'en': 'Our Services', 'bg': 'Нашите услуги'},
        'hero_subtitle': {'en': 'Innovative solutions tailored for every engineering need.', 'bg': 'Иновативни решения за всяко инженерно предизвикателство.'},
        'svc1_title': {'en': 'Conceptual & Technical Design', 'bg': 'Идейно и техническо проектиране'},
        'svc1_desc': {'en': 'From initial concepts to detailed designs, we plan and execute robust engineering projects.', 'bg': 'От първоначални идеи до детайлни проекти, ние планираме и реализираме стабилни инженерни проекти.'},
        'svc2_title': {'en': 'Simulation & Analysis', 'bg': 'Симулация и анализ'},
        'svc2_desc': {'en': 'State-of-the-art simulation tools to ensure efficiency and reliability in energy systems.', 'bg': 'Нови симулационни инструменти за гарантиране на ефективност и надеждност в енергийните системи.'},
        'svc3_title': {'en': 'Structural & Strength Analysis', 'bg': 'Якостен анализ'},
        'svc3_desc': {'en': 'Comprehensive quality checks and analysis ensuring compliance and structural integrity.', 'bg': 'Пълноценни анализи гарантиращи качество и структурна цялост.'},
        'svc4_title': {'en': 'Custom Mechanical Design', 'bg': 'Персонализирано механично проектиране'},
        'svc4_desc': {'en': 'Tailored designs for components, assemblies, and entire systems to match your needs.', 'bg': 'Персонализирани решения за детайли, събрания и цели системи според вашите нужди.'},
    },
    'contact': {
        'page_title': {'en': 'Contact Us', 'bg': 'Свържете се с нас'},
        'page_desc': {'en': 'Get in touch with S3 Synergy Ltd for any inquiries regarding our engineering solutions. We are here to help you.', 'bg': 'Свържете се с S3 Synergy Ltd за въпроси относно нашите инженерни решения. Ние сме тук, за да ви помогнем.'},
        'phone_label': {'en': 'Phone:', 'bg': 'Телефон:'},
        'phone_value': {'en': '+359 898 243 453', 'bg': '+359 898 243 453'},
        'email_label': {'en': 'Email:', 'bg': 'Имейл:'},
        'email_value': {'en': 's3_synergy@abv.bg', 'bg': 's3_synergy@abv.bg'},
        'form_name': {'en': 'Name:', 'bg': 'Име:'},
        'form_email': {'en': 'Email:', 'bg': 'Имейл:'},
        'form_message': {'en': 'Message:', 'bg': 'Съобщение:'},
        'form_submit': {'en': 'Send Message', 'bg': 'Изпрати съобщение'},
    },
    'projects': {
        'hero_eyebrow': {'en': 'OUR WORK', 'bg': 'НАШАТА РАБОТА'},
        'hero_title': {'en': 'Project Portfolio', 'bg': 'Портфолио Проекти'},
        'hero_desc': {'en': 'A selection of engineering projects delivered across energy generation, nuclear facilities, and industrial infrastructure.', 'bg': 'Подбор от инженерни проекти, реализирани в сферата на енергетиката, ядрените съоръжения и промишлената инфраструктура.'},
        'cta_title': {'en': 'Interested in Working Together?', 'bg': 'Заинтересовани сте от съвместна работа?'},
        'cta_desc': {'en': 'Tell us about your project and we will get back to you.', 'bg': 'Разкажете ни за вашия проект и ние ще се свържем с вас.'},
        'cta_btn': {'en': 'Contact Us', 'bg': 'Свържете се с нас'},
        'p1_tag': {'en': 'Nuclear', 'bg': 'Ядрена'},
        'p1_title': {'en': 'Drain Tank Design for Plasma Melting at NPP Kozloduy', 'bg': 'Резервоар за оттичане, плазмено топене, АЕЦ Козлодуй'},
        'p1_date': {'en': 'Oct 2016 – Present', 'bg': 'Окт 2016 – До момента'},
        'p1_desc': {'en': 'Detailed design with innovative planning and stress calculations to optimize efficiency.', 'bg': 'Детайлен проект с иновативно планиране и изчисления за оптимизация на ефективността.'},
        'p2_tag': {'en': 'Nuclear', 'bg': 'Ядрена'},
        'p2_title': {'en': 'Protection Shields for Pump Shafts at NPP Kozloduy', 'bg': 'Защитни екрани за вертикални валове'},
        'p2_date': {'en': 'Jun 2016 – Present', 'bg': 'Юни 2016 – До момента'},
        'p2_desc': {'en': 'Robust design ensuring long-term durability and regulatory compliance.', 'bg': 'Здрав проект за осигуряване на издръжливост и съответствие с нормативите.'},
        'p3_tag': {'en': 'Industrial', 'bg': 'Индустриален'},
        'p3_title': {'en': 'Storage Bunker with Screw Conveying System', 'bg': 'Складов резервоар с винтова система'},
        'p3_date': {'en': 'May 2016 – Present', 'bg': 'Май 2016 – До момента'},
        'p3_desc': {'en': 'Detailed mechanical design and stress calculations for a 90 m³ bunker.', 'bg': 'Детайлен механичен проект и изчисления за резервоар с вместимост 90 м³.'},
        'p4_tag': {'en': 'Energy', 'bg': 'Енергетика'},
        'p4_title': {'en': 'Reconstruction of Boilers KA-12 at TPP Maritsa East 2', 'bg': 'Реконструкция на котлите KA-12, ТЕЦ Марица Изток 2'},
        'p4_date': {'en': 'Jan 2016 – Present', 'bg': 'Януари 2016 – До момента'},
        'p4_desc': {'en': 'Improving combustion efficiency and reducing NOx emissions with an OFA system design.', 'bg': 'Подобряване на горенето и намаляване на NOx емисиите с дизайн на OFA система.'},
        'p5_tag': {'en': 'Energy', 'bg': 'Енергетика'},
        'p5_title': {'en': 'Reconstruction of Boilers KA-7 & KA-8 at TPP Maritsa East 2', 'bg': 'Реконструкция на котлите KA-7 & KA-8, ТЕЦ Марица Изток 2'},
        'p5_date': {'en': 'Sep 2015 – Present', 'bg': 'Сеп 2015 – До момента'},
        'p5_desc': {'en': 'Enhanced design for fuel efficiency and significant emission reduction.', 'bg': 'Подобрен проект за ефективност на горивото и значително намаляване на емисиите.'},
        'p6_tag': {'en': 'Industrial', 'bg': 'Индустриален'},
        'p6_title': {'en': 'Rectangular Shutter Valve for Flue Gases', 'bg': 'Правоъгълен клапан за фумни газове'},
        'p6_date': {'en': 'May 2015 – Present', 'bg': 'Май 2015 – До момента'},
        'p6_desc': {'en': 'Innovative valve design for improved control and regulation of flue gas flow.', 'bg': 'Иновативен дизайн на клапан за по-добър контрол и регулиране на потока на фумни газове.'},
        'p7_tag': {'en': 'Nuclear', 'bg': 'Ядрена'},
        'p7_title': {'en': 'Reserved Suction Pipe for Decarbonized Water Pumps at NPP Kozloduy', 'bg': 'Резервна тръба за засмукване, АЕЦ Козлодуй'},
        'p7_date': {'en': 'Aug 2014 – Present', 'bg': 'Авг 2014 – До момента'},
        'p7_desc': {'en': 'Thermal stress calculations integrated into dedicated pipe designs for critical pump systems.', 'bg': 'Интегрирани изчисления за топлинен стрес при проектиране на тръби за критични помпени системи.'},
        'p8_tag': {'en': 'Nuclear', 'bg': 'Ядрена'},
        'p8_title': {'en': 'Design, Delivery, and Installation of Service Water Filters', 'bg': 'Проектиране и монтаж на филтри за технологична вода'},
        'p8_date': {'en': 'Aug 2014 – Present', 'bg': 'Авг 2014 – До момента'},
        'p8_desc': {'en': 'Mechanical design for water filter projects in association with Atomtoploproekt Ltd.', 'bg': 'Механична част от проекти за филтри за вода, в сътрудничество с Atomtoploproekt Ltd.'},
        'p9_tag': {'en': 'Nuclear', 'bg': 'Ядрена'},
        'p9_title': {'en': 'Process Water Filters Replacement for Units 5 & 6 at NPP Kozloduy', 'bg': 'Замяна на филтри за технологична вода, блокове 5 и 6, АЕЦ Козлодуй'},
        'p9_date': {'en': 'Mar 2014 – Present', 'bg': 'Март 2014 – До момента'},
        'p9_desc': {'en': 'Replacement design with updated stress calculations and specifications, implemented by Hydac GmbH.', 'bg': 'Проект за замяна на филтри с нови изчисления за якост, изпълнен от Hydac GmbH.'},
    },
    'conceptual': {
        'hero_eyebrow': {'en': 'Engineering Services', 'bg': 'Инженерни услуги'},
        'hero_title': {'en': 'Conceptual & Technical Design', 'bg': 'Идейно и техническо проектиране'},
        'hero_desc': {'en': 'From the first sketch to fully approved working drawings — we translate engineering ambitions into precise, regulation-ready documentation.', 'bg': 'От първата скица до напълно одобрени работни чертежи — превръщаме инженерните идеи в точна, нормативно съобразена документация.'},
        'intro_h2': {'en': 'Turning Vision into Engineering Reality', 'bg': 'Превръщаме визията в инженерна реалност'},
        'intro_p1': {'en': 'Our team guides each project from abstract concept through technical analysis to construction-ready documentation. We apply rigorous engineering methodology while remaining responsive to client needs — delivering accurate, auditable, and fully compliant design packages on time.', 'bg': 'Нашият екип ръководи всеки проект от абстрактна концепция, през технически анализ, до документация готова за строителство. Прилагаме строга методология, оставайки гъвкави спрямо нуждите на клиента.'},
        'hl1': {'en': 'Feasibility studies with detailed risk assessment', 'bg': 'Проучвания за осъществимост с оценка на риска'},
        'hl2': {'en': 'Compliance with Bulgarian and EU engineering standards', 'bg': 'Съответствие с български и европейски норми'},
        'hl3': {'en': 'Iterative client review cycles at every phase', 'bg': 'Итеративни цикли на преглед с клиента на всяка фаза'},
        'hl4': {'en': '2D drafting and 3D parametric CAD modelling', 'bg': '2D чертежи и 3D параметрично CAD моделиране'},
        'hl5': {'en': 'Stamped documentation accepted by regulatory authorities', 'bg': 'Заверена документация, приета от регулаторни органи'},
        'scope_label': {'en': 'Documentation Phases', 'bg': 'Фази на документацията'},
        'scope1': {'en': 'Conceptual Documentation', 'bg': 'Идейна документация'},
        'scope2': {'en': 'Technical Documentation', 'bg': 'Техническа документация'},
        'scope3': {'en': 'Working Documentation', 'bg': 'Работна документация'},
        'process_h2': {'en': 'Design Process', 'bg': 'Проектантски процес'},
        'process_p': {'en': 'A structured four-phase workflow that eliminates ambiguity and keeps every stakeholder aligned from the first meeting to the final stamp.', 'bg': 'Структуриран четирифазен процес, който елиминира неяснотите и поддържа всички заинтересовани страни в съответствие.'},
        'tl1_h3': {'en': 'Discovery & Requirements', 'bg': 'Проучване и изисквания'},
        'tl1_p': {'en': 'In-depth client workshops to capture functional needs, site constraints, regulatory obligations, and budget parameters. Nothing proceeds until the scope is agreed in writing.', 'bg': 'Задълбочени работни срещи за улавяне на функционални нужди, ограничения и нормативни изисквания. Нищо не продължава докато обхватът не е потвърден писмено.'},
        'tl2_h3': {'en': 'Conceptual Design', 'bg': 'Идейно проектиране'},
        'tl2_p': {'en': "Schematic layouts, preliminary sizing, and alternative-option studies — enough detail to fix the project's direction with confidence and present it to stakeholders for approval.", 'bg': 'Схематични компоновки, предварително оразмеряване и изследване на алтернативи — достатъчно детайли за уверена посока и представяне на заинтересованите страни.'},
        'tl3_h3': {'en': 'Technical Documentation', 'bg': 'Техническа документация'},
        'tl3_p': {'en': 'Detailed calculations, specifications, material schedules, and fully dimensioned drawings — produced to the applicable standard and ready for authority submission.', 'bg': 'Детайлни изчисления, спецификации и напълно размерени чертежи — изготвени по приложимия стандарт и готови за административно подаване.'},
        'tl4_h3': {'en': 'Review & Handover', 'bg': 'Преглед и предаване'},
        'tl4_p': {'en': 'Internal QA check, client sign-off, regulatory submission support, and a complete indexed documentation package handed over in agreed formats.', 'bg': 'Вътрешна проверка за качество, одобрение от клиента и пълен индексиран пакет с документация, предаден в договорени формати.'},
        'deliv_h2': {'en': 'What We Deliver', 'bg': 'Какво предоставяме'},
        'deliv_p': {'en': 'Every engagement produces a concrete, auditable output — not just advice.', 'bg': 'Всяко сътрудничество произвежда конкретен, проверим резултат.'},
        'def1_h3': {'en': 'Feasibility Studies', 'bg': 'Проучвания за осъществимост'},
        'def1_p': {'en': 'Technical and economic viability analysis before resources are committed to detailed design — identifying critical risks and go/no-go criteria.', 'bg': 'Технически и икономически анализ на осъществимостта преди ангажиране на ресурси — идентифициране на критични рискове.'},
        'def2_h3': {'en': 'Conceptual Schematics', 'bg': 'Идейни схеми'},
        'def2_p': {'en': 'Clear, communicable layout drawings that anchor design decisions and align all project stakeholders before detailed work begins.', 'bg': 'Ясни, комуникативни чертежи на компоновката, закрепващи проектните решения преди детайлната работа.'},
        'def3_h3': {'en': 'Technical Specifications', 'bg': 'Технически спецификации'},
        'def3_p': {'en': 'Comprehensive material, performance, and quality specifications suitable for procurement and competitive tendering.', 'bg': 'Изчерпателни спецификации за материали, производителност и качество, подходящи за доставки и търгове.'},
        'def4_h3': {'en': '3D CAD Modelling', 'bg': '3D CAD моделиране'},
        'def4_p': {'en': 'Parametric solid models supporting clash detection, simulation input, and manufacturing drawing generation from a single source of truth.', 'bg': 'Параметрични модели, поддържащи засичане на сблъсъци, симулации и генериране на производствени чертежи.'},
        'def5_h3': {'en': 'Regulatory Compliance', 'bg': 'Нормативно съответствие'},
        'def5_p': {'en': 'Documentation formatted and stamped to satisfy Bulgarian NSI, Eurocode, and EU Directive requirements — ready for submission without amendment.', 'bg': 'Документация, форматирана и заверена за НСИ, Еврокод и директиви на ЕС — готова за подаване без изменения.'},
        'def6_h3': {'en': 'Client Collaboration', 'bg': 'Сътрудничество с клиенти'},
        'def6_p': {'en': 'Structured review meetings, shared model access, and clear revision tracking throughout the design lifecycle — no surprises at handover.', 'bg': 'Структурирани прегледи, споделен достъп до модели и ясно проследяване на ревизии — без изненади при предаването.'},
        'std_h3': {'en': 'Standards & Tools', 'bg': 'Стандарти и инструменти'},
        'cta_h2': {'en': 'Ready to Start Your Project?', 'bg': 'Готови да стартирате вашия проект?'},
        'cta_p': {'en': 'Tell us about your engineering challenge. We will assess it, scope it, and give you a clear path forward.', 'bg': 'Разкажете ни за вашето инженерно предизвикателство. Ще го оценим и ще ви дадем ясен план.'},
        'cta_btn1': {'en': 'Get in Touch', 'bg': 'Свържете се с нас'},
        'cta_btn2': {'en': 'All Services', 'bg': 'Всички услуги'},
    },
    'modeling': {
        'hero_eyebrow': {'en': 'Engineering Services', 'bg': 'Инженерни услуги'},
        'hero_title': {'en': 'Simulation & Analysis', 'bg': 'Симулация и анализ'},
        'hero_desc': {'en': 'Virtual testing at any scale — we model, simulate, and validate energy systems before a single component is manufactured, eliminating costly surprises in the field.', 'bg': 'Виртуално изпитване в произволен мащаб — моделираме и валидираме системи преди производство, елиминирайки скъпи изненади на обекта.'},
        'intro_h2': {'en': 'Predict, Optimise, Validate — Before You Build', 'bg': 'Предвиждайте, оптимизирайте и валидирайте — преди да строите'},
        'intro_p1': {'en': 'Physical prototyping is expensive and slow. Our simulation workflows let you explore operating conditions digitally, identify failure modes early, and arrive at an optimal design with mathematical certainty — compressing time-to-production and reducing material waste.', 'bg': 'Физическото прототипиране е скъпо и бавно. Нашите симулационни процеси ви позволяват да изследвате работни условия дигитално и да достигнете оптимален дизайн с математическа сигурност.'},
        'intro_p2': {'en': 'Every simulation study we deliver includes rigorous mesh-independence verification, clearly documented boundary conditions, and a professional engineering report — not just result screenshots.', 'bg': 'Всяко симулационно изследване включва строга верификация на мрежата, ясно документирани гранични условия и професионален инженерен доклад.'},
        'feat1': {'en': 'Coupled thermal, fluid, and mechanical simulations', 'bg': 'Свързани топлинни, флуидни и механични симулации'},
        'feat2': {'en': 'Energy system efficiency and loss quantification', 'bg': 'Анализ на ефективността и загубите в енергийни системи'},
        'feat3': {'en': 'Transient and steady-state analyses', 'bg': 'Преходни и установени анализи'},
        'feat4': {'en': 'Validated against physical test data where available', 'bg': 'Валидирани спрямо физически данни при наличност'},
        'feat5': {'en': 'Parametric sweeps across multiple operating points', 'bg': 'Параметрично сканиране на множество работни точки'},
        'feat6': {'en': 'Professionally formatted engineering reports', 'bg': 'Професионално форматирани инженерни доклади'},
        'caps_h2': {'en': 'Simulation Capabilities', 'bg': 'Симулационни възможности'},
        'caps_p': {'en': 'We cover the full spectrum of physics relevant to industrial energy systems.', 'bg': 'Обхващаме пълния спектър от физика, релевантна за индустриалните енергийни системи.'},
        'cap1_title': {'en': 'Computational Fluid Dynamics', 'bg': 'Изчислителна хидрогазодинамика'},
        'cap1_body': {'en': 'Flow field mapping, pressure drop characterisation, and mixing efficiency studies for ducts, heat exchangers, and process vessels. Turbulence modelling is selected and justified per case.', 'bg': 'Картографиране на полето на скоростите, характеристики на пад на налягане и ефективност на смесване за въздуховоди, топлообменници и съдове.'},
        'cap2_title': {'en': 'Thermal Analysis', 'bg': 'Термичен анализ'},
        'cap2_body': {'en': 'Steady-state and transient heat transfer — conduction, convection, and radiation — across complex multi-material assemblies. Results are used directly to set thermal insulation and cooling requirements.', 'bg': 'Топлопренос в стационарен и преходен режим — провеждане, конвекция и лъчение — в сложни многоматериални възли.'},
        'cap3_title': {'en': 'Energy System Optimisation', 'bg': 'Оптимизация на енергийни системи'},
        'cap3_body': {'en': 'Whole-system energy balance modelling to maximise output and reduce losses in pipelines, heat networks, and conversion plant.', 'bg': 'Моделиране на енергийния баланс на цялата система за максимизиране на производителността и намаляване на загубите.'},
        'cap4_title': {'en': 'Dynamic System Modelling', 'bg': 'Динамично моделиране на системи'},
        'cap4_body': {'en': 'Control-system and process-level dynamics — start-up sequences, transient loads, and stability margins under varying demand conditions.', 'bg': 'Динамика на системи за управление и процесно ниво — последователности на пуск, преходни товари и граници на стабилност.'},
        'cap5_title': {'en': 'Fatigue & Lifecycle Prediction', 'bg': 'Предсказване на умора и жизнен цикъл'},
        'cap5_body': {'en': 'Stress-life and strain-life fatigue analysis combined with creep modelling to forecast service intervals and component retirement.', 'bg': 'Анализ на умора и пълзене за прогнозиране на интервали на поддръжка и оставащ ресурс.'},
        'cap6_title': {'en': 'Structural FEA', 'bg': 'Структурен МКЕ'},
        'cap6_body': {'en': 'Linear and non-linear finite element analysis for mechanical components under thermal, pressure, and mechanical loading.', 'bg': 'Линеен и нелинеен МКЕ за механични компоненти под термично, налягателно и механично натоварване.'},
        'steps_h2': {'en': 'How We Run a Simulation Study', 'bg': 'Как провеждаме симулационно изследване'},
        'steps_p': {'en': 'Rigorous setup and post-processing discipline separates useful simulation from expensive noise.', 'bg': 'Строгата подготовка и обработка на резултатите отличават полезната симулация от скъп шум.'},
        'step1_h3': {'en': 'Problem Definition', 'bg': 'Дефиниране на задачата'},
        'step1_p': {'en': 'Governing physics, key performance indicators, boundary conditions, and acceptable margins — agreed before any model is built.', 'bg': 'Управляваща физика, КПИ, гранични условия и допустими отклонения — договорени преди изграждане на модела.'},
        'step2_h3': {'en': 'Model & Mesh', 'bg': 'Модел и мрежа'},
        'step2_p': {'en': 'Geometry simplification, material property assignment, and mesh-independence studies to ensure accurate, efficient solutions.', 'bg': 'Опростяване на геометрията, материални свойства и изследвания за независимост от мрежата.'},
        'step3_h3': {'en': 'Simulation & Iteration', 'bg': 'Симулация и итерация'},
        'step3_p': {'en': 'Parametric sweeps across load cases, operating points, and geometry variants — finding the optimal configuration systematically.', 'bg': 'Параметрично сканиране на товарни случаи, работни точки и геометрични варианти за намиране на оптимум.'},
        'step4_h3': {'en': 'Results & Report', 'bg': 'Резултати и доклад'},
        'step4_p': {'en': 'Post-processed visualisations, quantified conclusions, and design recommendations with clear engineering justification.', 'bg': 'Обработени визуализации, количествени изводи и препоръки с ясна инженерна обосновка.'},
        'std_h3': {'en': 'Tools & Standards', 'bg': 'Инструменти и стандарти'},
        'cta_h2': {'en': 'See Your System in Action — Virtually', 'bg': 'Вижте вашата система в действие — виртуално'},
        'cta_p': {'en': 'Share your system geometry and operating conditions. We will scope a simulation study and show you what the data reveals.', 'bg': 'Споделете геометрията и работните условия на вашата система. Ще определим обхвата на симулационното изследване.'},
        'cta_btn1': {'en': 'Discuss Your Project', 'bg': 'Обсъдете вашия проект'},
        'cta_btn2': {'en': 'All Services', 'bg': 'Всички услуги'},
    },
    'strength': {
        'hero_eyebrow': {'en': 'Engineering Services', 'bg': 'Инженерни услуги'},
        'hero_title': {'en': 'Structural & Strength Analysis', 'bg': 'Якостен анализ'},
        'hero_desc': {'en': 'Every pipeline, duct, and structure we analyse carries the weight of certainty — code-compliant calculations backed by rigorous finite element analysis.', 'bg': 'Всеки тръбопровод и конструкция, която анализираме, носи тежестта на сигурността — изчисления в съответствие с нормите, подкрепени от строг МКЕ анализ.'},
        'callout_p': {'en': 'We produce stamped calculation packages that satisfy regulatory bodies, clients, and insurers — built on actual load combinations, not idealised assumptions.', 'bg': 'Издаваме заверени изчислителни пакети, удовлетворяващи регулаторни органи, клиенти и застрахователи — базирани на реални товарни комбинации, не идеализирани предположения.'},
        'hl1': {'en': 'Full Eurocode 3 and EN 13480 pipeline compliance', 'bg': 'Пълно съответствие с Еврокод 3 и EN 13480'},
        'hl2': {'en': 'FEA with mesh convergence verification', 'bg': 'МКЕ с верификация на сходимост на мрежата'},
        'hl3': {'en': 'Static, dynamic, seismic, and fatigue load cases', 'bg': 'Статични, динамични, сеизмични товарни случаи и умора'},
        'hl4': {'en': 'Support and hanger design where required', 'bg': 'Проектиране на опори при необходимост'},
        'hl5': {'en': 'Reports accepted by Bulgarian regulatory authorities', 'bg': 'Доклади, приети от български регулаторни органи'},
        'intro_h2': {'en': 'Structural Integrity You Can Sign Off On', 'bg': 'Структурна цялост, на която можете да разчитате'},
        'intro_p1': {'en': 'We perform detailed strength analyses for pipelines, air ducts, gas ducts, and associated support structures. Our finite element models are built with construction tolerances and actual load combinations in mind — not textbook idealisations.', 'bg': 'Извършваме детайлни якостни анализи на тръбопроводи, въздуховоди, газоходи и свързани носещи конструкции.'},
        'intro_p2': {'en': 'The final deliverable is a complete, indexed calculation package — load inputs, FEA appendices, code checks, and a stamped engineering report ready for submission to any relevant authority.', 'bg': 'Крайният резултат е пълен, индексиран изчислителен пакет — входни товари, МКЕ приложения, нормативни проверки и заверен инженерен доклад.'},
        'wf_h2': {'en': 'Analysis Workflow', 'bg': 'Аналитичен работен процес'},
        'wf_p': {'en': 'From load definition to signed deliverable — a transparent, traceable process with no gaps.', 'bg': 'От дефиниране на товара до подписан резултат — прозрачен, проследим процес без пропуски.'},
        'row1_title': {'en': 'Load Case Definition', 'bg': 'Дефиниране на товарни случаи'},
        'row1_desc': {'en': 'Cataloguing all relevant loads — dead, live, thermal, wind, seismic, pressure transients — and forming code-prescribed combinations. Agreed with the client before modelling begins.', 'bg': 'Каталогизиране на всички релевантни товари и формиране на нормативно предписани комбинации. Договорени с клиента преди моделирането.'},
        'row2_title': {'en': 'FE Model Setup', 'bg': 'Изграждане на МКЕ модел'},
        'row2_desc': {'en': 'Geometry preparation, element selection, material libraries, boundary conditions, and mesh refinement studies to guarantee solution accuracy before the solver is run.', 'bg': 'Подготовка на геометрията, избор на елементи, материални библиотеки и изследвания за точност на решението преди стартиране на солвера.'},
        'row3_title': {'en': 'Analysis & Code Check', 'bg': 'Анализ и нормативна проверка'},
        'row3_desc': {'en': 'Running the FE solver, extracting stress resultants, and performing systematic code utilisation checks against the governing standard — every check referenced and traceable.', 'bg': 'Стартиране на МКЕ солвера, извличане на напрежения и системна нормативна проверка — всяка проверка е референцирана и проследима.'},
        'row4_title': {'en': 'Documentation & Sign-Off', 'bg': 'Документация и заверка'},
        'row4_desc': {'en': 'Complete calculation notes, FEA appendices, drawings, and a stamped engineering report ready for submission to the relevant authority or client QA system.', 'bg': 'Пълни изчислителни записки, МКЕ приложения, чертежи и заверен инженерен доклад за подаване до съответния орган.'},
        'spec_h2': {'en': 'Analysis Specialisations', 'bg': 'Аналитични специализации'},
        'spec_p': {'en': 'We go where generic FEA consultants stop — pipeline stress, duct expansion, and specialist seismic work.', 'bg': 'Отиваме там, където общите МКЕ консултанти спират — тръбопроводни напрежения, разширения и сеизмична работа.'},
        'cap1_h3': {'en': 'Static Stress Analysis', 'bg': 'Статичен якостен анализ'},
        'cap1_p': {'en': 'Linear and non-linear static FEA for pressure vessels, brackets, nozzles, and structural steel assemblies under combined loading scenarios.', 'bg': 'Линеен и нелинеен статичен МКЕ за съдове под налягане, конзоли, дюзи и стоманени конструкции под комбинирани товари.'},
        'cap2_h3': {'en': 'Buckling & Stability', 'bg': 'Изкълчване и стабилност'},
        'cap2_p': {'en': 'Eigenvalue and non-linear buckling analysis for slender columns, shells, thin-walled ducts, and long-span pipelines operating under external or axial compression.', 'bg': 'Собствено-стойностен и нелинеен анализ на изкълчване за тънкостенни конструкции и дълги тръбопроводи.'},
        'cap3_h3': {'en': 'Pipeline Stress Analysis', 'bg': 'Якостен анализ на тръбопроводи'},
        'cap3_p': {'en': 'Sustained, expansion, and occasional load categories per EN 13480 and ASME B31 — including support spacing optimisation and nozzle load reporting.', 'bg': 'Поддържани, разширителни и случайни товарни категории по EN 13480 и ASME B31, включително оптимизация на разстоянията между опорите.'},
        'cap4_h3': {'en': 'Seismic Assessment', 'bg': 'Сеизмична оценка'},
        'cap4_p': {'en': 'Response-spectrum and time-history analyses for equipment, pipework, and support structures in seismically active zones per EN 1998.', 'bg': 'Анализ на отговор и времеви хистограми за оборудване и конструкции в сеизмично активни зони по EN 1998.'},
        'cap5_h3': {'en': 'Air & Gas Duct Analysis', 'bg': 'Анализ на въздуховоди и газоходи'},
        'cap5_p': {'en': 'Rectangular and circular duct strength checks including internal and external pressure, thermal expansion, and support spacing optimisation to applicable standards.', 'bg': 'Якостни проверки на правоъгълни и кръгли въздуховоди — вътрешно и външно налягане, температурно разширение и оптимизация на опори.'},
        'cap6_h3': {'en': 'Compliance Reporting', 'bg': 'Нормативна отчетност'},
        'cap6_p': {'en': 'Stamped calculation packages with full traceability — load inputs, code references, applied safety factors, and clear interpretation of results for each governing load case.', 'bg': 'Заверени изчислителни пакети с пълна проследимост — входни данни, стандарти, коефициенти на сигурност и интерпретация на резултатите.'},
        'std_h3': {'en': 'Codes & Software', 'bg': 'Нормативи и софтуер'},
        'cta_h2': {'en': 'Need a Strength Analysis Certificate?', 'bg': 'Нуждаете се от сертификат за якостен анализ?'},
        'cta_p': {'en': 'Send us your isometric drawings and design data. We will produce a stamped, authority-ready calculation package.', 'bg': 'Изпратете ни изометричните чертежи и проектните данни. Ще изготвим заверен, готов за органите изчислителен пакет.'},
        'cta_btn1': {'en': 'Request Analysis', 'bg': 'Заявете анализ'},
        'cta_btn2': {'en': 'All Services', 'bg': 'Всички услуги'},
    },
    'design': {
        'hero_eyebrow': {'en': 'Engineering Services', 'bg': 'Инженерни услуги'},
        'hero_title': {'en': 'Custom Mechanical Design', 'bg': 'Персонализирано механично проектиране'},
        'hero_desc': {'en': 'One-off components, complex assemblies, bespoke machines, and complete industrial facilities — designed to your exact specification.', 'bg': 'Единични компоненти, сложни възли, персонализирани машини и цели промишлени съоръжения — проектирани по ваши точни изисквания.'},
        'statement_before': {'en': 'Off-the-shelf rarely fits perfectly.', 'bg': 'Стандартните решения рядко са идеални.'},
        'statement_bold': {'en': 'We design mechanical systems from the ground up', 'bg': 'Ние проектираме механични системи от нулата'},
        'statement_after': {'en': '— or reverse-engineer and improve existing ones — producing fully toleranced, manufacturing-ready documentation that goes straight to the workshop floor without interpretation.', 'bg': '— или обратно-инженерираме и подобряваме съществуващи — произвеждайки документация готова директно за производствения цех.'},
        'intro_h2': {'en': 'Engineered for Your Application', 'bg': 'Проектирано за вашето приложение'},
        'intro_p1': {'en': 'Our mechanical design service covers the full scope — from a single precision component to an entire production facility. We handle geometry, material selection, tolerancing, and manufacturing documentation as a unified service with a single point of accountability.', 'bg': 'Нашата услуга за механично проектиране обхваща пълния обхват — от единичен прецизен компонент до цяло производствено съоръжение.'},
        'intro_p2': {'en': 'Every drawing that leaves our office carries a clear revision history, traceable material specifications, and tolerancing that reflects the actual capabilities of the manufacturing process — not generic textbook values.', 'bg': 'Всеки чертеж, напускащ нашия офис, съдържа ясна история на ревизиите, проследими спецификации на материалите и толерансиране, отразяващо реалните производствени възможности.'},
        'scope_label': {'en': 'Design Scope', 'bg': 'Обхват на проектиране'},
        'scope1': {'en': 'Component & Part Design', 'bg': 'Проектиране на детайли'},
        'scope2': {'en': 'Assembly & Sub-Assembly', 'bg': 'Сглобки и подсглобки'},
        'scope3': {'en': 'Machine & Facility Design', 'bg': 'Машини и съоръжения'},
        'scope4': {'en': 'Reverse Engineering', 'bg': 'Обратно инженерство'},
        'process_h2': {'en': 'From Brief to Build-Ready', 'bg': 'От брифа до готовност за производство'},
        'process_p': {'en': 'A disciplined design sequence that eliminates rework and produces documentation your machine shop can execute first time.', 'bg': 'Дисциплинирана последователност на проектиране, елиминираща преработките и произвеждаща документация изпълнима от първия път.'},
        'proc1_h3': {'en': 'Brief & Specification', 'bg': 'Бриф и спецификация'},
        'proc1_p': {'en': 'Functional requirements, interface constraints, environmental conditions, and cost targets translated into a frozen engineering specification — agreed before any geometry is created.', 'bg': 'Функционални изисквания, ограничения на интерфейси и целеви разходи, преведени в замразена инженерна спецификация — договорена преди създаване на геометрия.'},
        'proc2_h3': {'en': 'Conceptual CAD Modelling', 'bg': 'Концептуално CAD моделиране'},
        'proc2_p': {'en': 'Parametric 3D models exploring configuration options — layout, kinematics, accessibility, and serviceability — presented for client review before detail design begins.', 'bg': 'Параметрични 3D модели, изследващи конфигурационни варианти — компоновка, кинематика и сервизна достъпност — представени за преглед преди детайлното проектиране.'},
        'proc3_h3': {'en': 'Detail Design & Tolerancing', 'bg': 'Детайлно проектиране и толерансиране'},
        'proc3_p': {'en': 'Full feature definition, GD&T callouts, surface finish requirements, and fit selection — every dimension carries engineering intent and is traceable to the specification.', 'bg': 'Пълна дефиниция на елементите, GD&T анотации, изисквания за повърхностна обработка и избор на посадки — всеки размер е проследим до спецификацията.'},
        'proc4_h3': {'en': 'Manufacturing Documentation', 'bg': 'Производствена документация'},
        'proc4_p': {'en': 'Approved part drawings, assembly instructions, bill of materials, material certifications, and inspection criteria — a complete manufacturing data pack ready for immediate procurement.', 'bg': 'Одобрени детайлни чертежи, инструкции за сглобяване, BOM и инспекционни критерии — пълен производствен пакет готов за незабавна доставка.'},
        'caps_h2': {'en': 'Design Capabilities', 'bg': 'Проектантски възможности'},
        'caps_p': {'en': 'From the smallest fitting to an entire production facility — we scale to match the complexity.', 'bg': 'От най-малкия фитинг до цяло производствено съоръжение — мащабираме се спрямо сложността.'},
        'cap1_h3': {'en': 'Component Design', 'bg': 'Проектиране на компоненти'},
        'cap1_p': {'en': 'Shafts, brackets, flanges, housings, and fastener selections — any individual part optimised for its specific load environment and intended manufacturing route.', 'bg': 'Валове, конзоли, фланци, корпуси — всеки отделен детайл, оптимизиран за своята товарна среда и производствен маршрут.'},
        'cap2_h3': {'en': 'Assembly Design', 'bg': 'Проектиране на възли'},
        'cap2_p': {'en': 'Multi-part assemblies with full interface management — clearance stack-up analysis, kinematics validation, and assembly sequence planning to ensure fit first time.', 'bg': 'Многодетайлни възли с управление на интерфейси, анализ на допустимите отклонения и планиране на последователността на сглобяване.'},
        'cap3_h3': {'en': 'Machine Design', 'bg': 'Проектиране на машини'},
        'cap3_p': {'en': 'Complete machine development from mechanism synthesis through drive selection, frame design, guarding, and CE declaration documentation per Machinery Directive 2006/42/EC.', 'bg': 'Пълна разработка на машини — от синтез на механизма, избор на задвижване и проектиране на рамата до декларация за CE по Директива за машини.'},
        'cap4_h3': {'en': 'Facility Engineering', 'bg': 'Проектиране на съоръжения'},
        'cap4_p': {'en': 'Integrated mechanical design at facility level — equipment layout, utility connections, access platforms, maintenance routes, and coordination with civil and electrical disciplines.', 'bg': 'Интегрирано механично проектиране на ниво съоръжение — компоновка на оборудването, свързване с комуналните услуги и координация с граждански и електрически дисциплини.'},
        'cap5_h3': {'en': 'Reverse Engineering', 'bg': 'Обратно инженерство'},
        'cap5_p': {'en': 'Physical measurement, 3D scanning, and reconstruction of legacy or obsolete parts — improved where required and re-documented to current drawing standards for modern manufacturing.', 'bg': 'Физическо измерване, 3D сканиране и реконструкция на остарели детайли — подобрени при необходимост и документирани по съвременни стандарти за производство.'},
        'cap6_h3': {'en': 'GD&T & Tolerancing', 'bg': 'GD&T и толерансиране'},
        'cap6_p': {'en': 'Functional tolerancing using ISO 1101 and ASME Y14.5 — worst-case and statistical stack-up analysis to balance achievable quality against manufacturing cost.', 'bg': 'Функционално толерансиране по ISO 1101 и ASME Y14.5 — анализ на допустимите отклонения за баланс между постижимо качество и производствени разходи.'},
        'std_h3': {'en': 'Standards & Tools', 'bg': 'Стандарти и инструменти'},
        'cta_h2': {'en': 'Have a Part That Does Not Exist Yet?', 'bg': 'Имате детайл, който все още не съществува?'},
        'cta_p': {'en': 'Tell us what it needs to do and the environment it operates in. We will design it, document it, and hand you a package your manufacturer can quote on immediately.', 'bg': 'Кажете ни какво трябва да прави и средата, в която ще работи. Ще го проектираме и ще ви предадем пакет, от който производителят може незабавно да направи оферта.'},
        'cta_btn1': {'en': 'Start a Design Brief', 'bg': 'Стартирайте бриф за проектиране'},
        'cta_btn2': {'en': 'All Services', 'bg': 'Всички услуги'},
    },
}
